
services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    command:
      # http://traefik.myvps.test:8080/
      # http://traefik.myvps.test:8080/dashboard/#/
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.myvps.test`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=web"

    ports:
      - "80:80"
      - "8080:8080"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik_proxy

  random-server-01:
    image: ghcr.io/mitchallen/random-server
    environment:
      - APP_NAME=random-01
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.random-server.rule=Host(`random.myvps.test`)"
      - "traefik.http.services.random-server.loadbalancer.server.port=3100"

  path1:
    image: ghcr.io/mitchallen/random-server
    environment:
      - APP_NAME=path1
      - BASE_PATH=/path1
      - SWAGGER_BASE_PATH=/path1
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.path1.rule=Host(`service.myvps.test`) && PathPrefix(`/path1`)"
      - "traefik.http.services.path1.loadbalancer.server.port=3100"

  path2:
    image: ghcr.io/mitchallen/random-server
    environment:
      - APP_NAME=path2
      - BASE_PATH=/path2
      - SWAGGER_BASE_PATH=/path2
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.path2.rule=Host(`service.myvps.test`) && PathPrefix(`/path2`)"
      - "traefik.http.services.path2.loadbalancer.server.port=3100"

networks:
  traefik_proxy:
    name: traefik_proxy
